/// <reference path="layui.util.d.ts" />
/// <reference path="layui.upload.d.ts" />
/// <reference path="layui.tree.d.ts" />
/// <reference path="layui.transfer.d.ts" />
/// <reference path="layui.table.d.ts" />
/// <reference path="layui.slider.d.ts" />
/// <reference path="layui.rate.d.ts" />
/// <reference path="layui.laypage.d.ts" />
/// <reference path="layui.laydate.d.ts" />
/// <reference path="layui.form.d.ts" />
/// <reference path="layui.layedit.d.ts" />
/// <reference path="layui.element.d.ts" />
/// <reference path="layui.flow.d.ts" />
/// <reference path="layui.colorpicker.d.ts" />
/// <reference path="layui.carousel.d.ts" />
/// <reference path="layui.layer.d.ts" />
/// <reference path="layui.d.ts" />

declare const layui: Layui.LayuiInstance;
declare const layer: Layui.ILayerStatic;